Fix sporadic 01_run.t failure -- "process is still running"
openSUSE/Mojo-IOLoop-ReadWriteProcess pull request #41
Opened 2021-12-10 09:20 UTC by cfconrad

We encountered flaky 01_run.t tests with the error looks like:
```
 #   Failed test 'process is still running'
 #   at t/01_run.t line 235.
 #          got: '0'
 #     expected: '1'
 # Looks like you failed 1 test of 38.

 #   Failed test 'process execute()'
 #   at t/01_run.t line 302.
```
It occurs in one out of ~300 runs. This fix assume, that we actually
send the SIGTERM before the executed script `term_trap.sh` has setup
it's traphandler to ignore such signal.

The fix just listen on STDOUT of the script to get informed, once the
sighandlers are setted and then continue.

A sleep would be ok as well, but it's harder to judge how long is a good
sleep :).

2021-12-10 09:21 UTC, cfconrad commented
Related to https://github.com/openSUSE/Mojo-IOLoop-ReadWriteProcess/issues/40
With this change, I have 1400 successful runs.

2021-12-10 10:07 UTC, Martchus approved these changes

2021-12-10 17:03 UTC, okurz requested changes
but now https://github.com/openSUSE/Mojo-IOLoop-ReadWriteProcess/runs/4481577319?check_suite_focus=true#step:6:432 failed. Also I suggest you run your tests with coverage analysis enabled. We have seen a couple of tests (in openQA, not here, though) that run very stable by themselves but when called within CI where coverage analysis slows down execution random errors crop up which point to race-conditions

2021-12-10 20:51 UTC, okurz commented
I have seen the update and all checks passed, congrats :) But, still, could you please ensure to run tests locally with coverage analysis enabled for verification?

2021-12-13 12:31 UTC, cfconrad commented
Done with 1479 iterations...

2021-12-13 16:58 UTC, okurz commented
> Done with 1479 iterations...

Could you please state what command you used for that so that coverage analysis is enabled?

2021-12-13 19:51 UTC, cfconrad commented
```bash
#!/bin/bash -e
count=0;
perl Build.PL

while true; do
    count=$(($count + 1 ));
    echo "LOOP $count";
    TEST_SHARED=1 TEST_SUBREAPER=1 cover -test -report codecovbash
done
```

And this patch 
```patch
diff --git a/Build.PL b/Build.PL
index ad9d29b..92f7a60 100644
--- a/Build.PL
+++ b/Build.PL
@@ -48,8 +48,9 @@ my %args = (
     script_files => [glob('script/*'), glob('bin/*')],
     PL_files => {},
 
-    test_files           => ((-d '.git' || $ENV{RELEASE_TESTING}) && -d 'xt') ? 't/ xt/' : 't/',
+    test_files           => 't/01_run.t',
     recursive_test_files => 1,
+    verbose => 1,
 
 
 );
```

2021-12-13 19:53 UTC, okurz approved these changes
Awesome, thx!

2021-12-13 19:54 UTC, merged